version: '3'
services:
    fdfs-trackerd:
        image: fdfs/tracker:0.4
        container_name: fdfs-tracker
        ports:
            - 22122:22122
            - 23000:23000
        environment:
            - IP=172.31.240.104
            - WEB_PORT=8088
            - FDFS_PORT=22122
        volumes:
            - /etc/locale.conf:/etc/locale.conf
            - ./data/tracker:/var/local/fdfs/tracker
        privileged: true
        networks: 
          - app
    fdfs-storage:
        image: fdfs/storage:0.4
        ports:
            - 8089:8088
        environment:
            - NGINX_CONF_FILE=/usr/local/nginx/conf/nginx.conf
            - TRACKERD_IP=fdfs-trackerd
            - WEB_PORT=8088
            - TRACKERD_PORT=22122
        volumes:
            - /home/docker/fdfs/data/storage:/home/yuqing/fastdfs
            - /home/docker/fdfs/data/nginx/conf:/usr/local/nginx/conf/
            - /etc/locale.conf:/etc/locale.conf
        privileged: true
        networks: 
          - app
    fdfs-video:
        image: fdfs/video:0.4
        ports:
            - 8089:7777
        environment:
          - FASTDFS_TRACKER_PORT=22122
          - PROXY=dfs-storage:8088
          - FASTDFS_TRACKER_IP=172.31.240.104
        privileged: true
        networks: 
          - app
networks:
  app:
    external: true
